version: "3.9"
services:
  pg_db:
    image: postgres:13.8
    container_name: pg_db
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PWD}"
      POSTGRES_DB: PG_Q_DB
      PG_DATA: /var/lib/postgresql/data
    networks:
      - postgres
    ports:
      - 5432:5432
    volumes:
      - .docker/pg_wallet/:/var/lib/postgresql/data
      - .docker:/docker-entrypoint-initdb.d

networks:
  postgres:
    driver: bridge
